random_seed: 42

monte_carlo:
  n_stars: 100000
  n_realizations: 100

stellar_mass:
  m_min: 0.1
  m_max_values: [20, 40, 60, 80, 100]

supernova:
  core_collapse_threshold: 8.0

  
Massengrenzen für Endzustände

Anzahl Sterne pro Population

Konfidenzniveau (68 %, 95 %)